# frozen_string_literal: true

URL_SEMANTIC_RELEASE = 'https://gitlab.com/gitlab-org/gitlab-ui/blob/master/CONTRIBUTING.md#conventional-commits'
SEMANTIC_COMMIT_TYPES = %w[build chore ci docs feat fix perf refactor revert style test].freeze

MAJOR_RELEASE = 1000
MINOR_RELEASE = 100
PATCH_RELEASE = 10
NO_RELEASE = 1

COMMIT_SUBJECT_MAX_LENGTH = 72
COMMIT_BODY_MAX_LENGTH = 72

# Perform various checks against commits. We're not using
# https://github.com/jonallured/danger-commit_lint because its output is not
# very helpful, and it doesn't offer the means of ignoring merge commits.

def fail_commit(commit, message)
  raise("#{commit.sha}: #{message}")
end

def warn_commit(commit, message)
  warn("#{commit.sha}: #{message}")
end

def lines_changed_in_commit(commit)
  commit.diff_parent.stats[:total][:lines]
end

def too_many_changed_lines?(commit)
  commit.diff_parent.stats[:total][:files] > 3 &&
    lines_changed_in_commit(commit) >= 30
end

def match_semantic_commit(text)
  text.match(/^(?<type>\w+)(?:\((?<scope>.+?)\))?:(?<description>.+?)$/)
end

def add_no_release_markdown
  markdown(<<~MARKDOWN)
    ## No release

    This Merge Request will trigger _no_ release.
    This either means, no commit neither the MR title warrant a semantic release (e.g. only updating CI config);
    or that all commits and/or the MR title are not properly formatted according to
    [conventional commits](#{URL_SEMANTIC_RELEASE}) rules, in the latter case, you should either:
    - Disable **Squash commits when merge request is accepted** and rewrite the commits history to
    format commit messages properly
    - Enable **Squash commits when merge request is accepted** and make sure the MR's title
    complies with conventional commits specifications
  MARKDOWN
end

def add_release_type_markdown(type)
  markdown(<<~MARKDOWN)
    ## \u{1f4e6} #{type.capitalize} ([conventional commits](#{URL_SEMANTIC_RELEASE}))
  MARKDOWN
end

def get_release_info(release_type)
  case release_type
  when MAJOR_RELEASE
    type = 'major release'
    bump = <<~BUMP
      This will bump the first part of the version number, e.g. `v1.2.3` -> `v2.0.0`.

      This means that GitLab UI has a breaking change.
    BUMP
  when MINOR_RELEASE
    type = 'minor release'
    bump = 'This will bump the second part of the version number, e.g. `v1.2.3` -> `v1.3.0`.'
  when PATCH_RELEASE
    type = 'patch release'
    bump = 'This will bump the third part of the version number, e.g. `v1.2.3` -> `v1.2.4`.'
  else
    warn 'This MR will trigger no release'
    add_no_release_markdown
    return
  end
  [type, bump]
end

def lint_commit(commit)
  # For now we'll ignore merge commits, as getting rid of those is a problem
  # separate from enforcing good commit messages.
  # We also ignore revert commits as they are well structured by Git already
  if commit.message.start_with?('Merge branch') || commit.message.start_with?('Revert "')
    return { failed: false, release: NO_RELEASE }
  end

  release = NO_RELEASE
  failures = false
  subject, separator, details = commit.message.split("\n", 3)

  if subject.length > COMMIT_SUBJECT_MAX_LENGTH
    fail_commit(
      commit,
      "The commit subject may not be longer than #{COMMIT_SUBJECT_MAX_LENGTH} characters"
    )

    failures = true
  end

  # Fail if a suggestion commit is used and squash is not enabled
  if commit.message.start_with?('Apply suggestion to') && !gitlab.mr_json['squash']
    fail_commit(
      commit,
      'If you are applying suggestions, squash needs to be enabled in the merge request'
    )

    failures = true
  end

  if subject.end_with?('.')
    fail_commit(commit, 'The commit subject must not end with a period')
    failures = true
  end

  if separator && !separator.empty?
    fail_commit(
      commit,
      'The commit subject and body must be separated by a blank line'
    )

    failures = true
  end

  details&.each_line do |line|
    line = line.strip

    next if line.length <= COMMIT_BODY_MAX_LENGTH

    url_size = line.scan(%r{(https?://\S+)}).sum { |(url)| url.length }

    # If the line includes a URL, we'll allow it to exceed 72 characters, but
    # only if the line _without_ the URL does not exceed this limit.
    next if line.length - url_size <= COMMIT_BODY_MAX_LENGTH

    fail_commit(
      commit,
      "The commit body should not contain more than #{COMMIT_BODY_MAX_LENGTH} characters per line"
    )

    failures = true
  end

  if !details && too_many_changed_lines?(commit)
    fail_commit(
      commit,
      'Commits that change 30 or more lines across at least three files ' \
        'must describe these changes in the commit body'
    )

    failures = true
  end

  if commit.message.match?(%r{([\w\-\/]+)?(#|!|&|%)\d+\b})
    fail_commit(
      commit,
      'Use full URLs instead of short references ' \
        '(`gitlab-org/gitlab-ce#123` or `!123`), as short references are ' \
        'displayed as plain text outside of GitLab'
    )

    failures = true
  end

  semantic_commit = match_semantic_commit(subject)

  if !semantic_commit
    warn_commit(commit, 'The commit is no proper semantic commit.')

    failures = true
  elsif !SEMANTIC_COMMIT_TYPES.include?(semantic_commit[:type])
    warn_commit(
      commit,
      "The Semantic commit type `#{semantic_commit[:type]}` is not a well-known semantic commit type."
    )

    failures = true
  elsif details&.match(/BREAKING CHANGE:/)
    release = MAJOR_RELEASE
  elsif semantic_commit[:type] == 'feat'
    release = MINOR_RELEASE
  elsif semantic_commit[:type] == 'perf' || semantic_commit[:type] == 'fix'
    release = PATCH_RELEASE
  end

  { failed: failures, release: release }
end

def lint_commits(commits)
  commits_with_status = commits.map { |commit| { commit: commit }.merge(lint_commit(commit)) }

  failed = commits_with_status.any? { |commit| commit[:failed] }

  max_release = commits_with_status.max { |a, b| a[:release] <=> b[:release] }

  if failed
    markdown(<<~MARKDOWN)
      ## Commit message standards

      One or more commit messages do not meet our Git commit message standards.
      For more information on how to write a good commit message, take a look at
      [Conventional commits](#{URL_SEMANTIC_RELEASE}).

      Here is an example of a good commit message:

          feat(progressbar): Improve rendering performance in Edge

          Our progressbar component was causing a lot of re-renders in Edge.
          This was caused by excessive re-rendering due to floating point errors
          in Edge's JavaScript engine.

          By utilizing the better-math library we avoid those calculation errors
          and we can achieve 120 rendering frames per second again.

      This is an example of a bad commit message:

          fixed progressbar

    MARKDOWN
  end

  return if gitlab.mr_json['squash']

  type, bump = get_release_info(max_release[:release])

  if type && bump
    add_release_type_markdown(type)
    markdown(<<~MARKDOWN)
      This Merge Request will trigger a _#{type}_ of GitLab UI, triggered by commit:
      #{max_release[:commit].sha}

      #{bump}
    MARKDOWN
  end
end

def lint_mr(mr)
  if mr && mr['squash']
    release = NO_RELEASE
    semantic_commit = match_semantic_commit(mr['title'])
    if !semantic_commit
      warn_commit(
        commit,
        'Your MR has **Squash commits when merge request is accepted** enabled but its title does not comply with conventional commits specifications'
      )

      failures = true
    elsif !SEMANTIC_COMMIT_TYPES.include?(semantic_commit[:type])
      warn_commit(
        commit,
        "The Semantic commit type `#{semantic_commit[:type]}` is not a well-known semantic commit type."
      )

      failures = true
    elsif semantic_commit[:type] == 'feat'
      release = MINOR_RELEASE
    elsif semantic_commit[:type] == 'perf' || semantic_commit[:type] == 'fix'
      release = PATCH_RELEASE
    end

    type, bump = get_release_info(release)

    if type && bump
      add_release_type_markdown(type)
      markdown(<<~MARKDOWN)
        This Merge Request will trigger a _#{type}_ of GitLab UI based on its title.

        #{bump}
      MARKDOWN
    end
  end
end

lint_commits(git.commits)
lint_mr(gitlab.mr_json)

if git.commits.length > 10
  warn(
    'This merge request includes more than 10 commits. ' \
      'Please rebase these commits into a smaller number of commits.'
  )
end
