<template>
  <gl-friendly-wrap
    text="LoremipsumdolorsitametconsecteturadipiscingelitseddoeiusmodtemporincididuntutlaboreetdoloremagnaaliquaLaoreetsuspendisseinterdumconsecteturliberoidfaucibusnisltinciduntLeoadiamsollicitudintemporideuAtultricesmitempusimperdietElitscelerisquemaurispellentesquepulvinarpellentesquehabitantmorbiNequealiquamvestibulummorbiblanditcursusAliquamultricessagittisorciaSenectusetnetusetmalesuadafamesacturpisegestasOrnarearcuodioutsemnullapharetradiamsitametIdconsecteturpurusutfaucibuspulvinarelementumintegerenimnequeCursusmattismolestieaiaculisateratpellentesqueOdiotempororcidapibusultricesiniaculisnuncsedOrcieulobortiselementumnibhtellusmolestieDolorpurusnonenimpraesentelementumfacilisisleovel"
    :symbols="['a', 'o']"
  />
</template>
