def changed_examples?
  files = (git.added_files + git.modified_files)
  files.any? { |file| file.end_with? ".example.vue" }
end

if changed_examples?
  warn(
    'This Merge Request either changed or added component examples (`.example.vue` files). '\
    'Note that examples should not be written in GitLab UI anymore. '\
    'Please consider moving them to `design.gitlab.com`. ' \
    'Read more about this here: https://gitlab.com/gitlab-org/gitlab-services/design.gitlab.com/-/blob/master/doc/component-examples.md.'
  )
end