// Component documentation
// ADD EXPORTS - needed for yarn generate:component. Do not remove
export { default as GlRichTextEditorDocumentation } from '../src/components/editors/rich_text_editor/rich_text_editor.documentation';
export { default as GlDropdownFormDocumentation } from '../src/components/base/dropdown/dropdown_form.documentation';
export { default as GlKeysetPaginationDocumentation } from '../src/components/base/keyset_pagination/keyset_pagination.documentation';
export { default as GlInputGroupTextDocumentation } from '../src/components/base/form/input_group_text/input_group_text.documentation';
export { default as GlFormTextDocumentation } from '../src/components/base/form/form_text/form_text.documentation';
export { default as GlFormComboboxDocumentation } from '../src/components/base/form/form_combobox/form_combobox.documentation';
export { default as GlGaugeChartDocumentation } from '../src/components/charts/gauge/gauge.documentation';
export { default as GlTokenSelectorDocumentation } from '../src/components/base/token_selector/token_selector.documentation';
export { default as GlNavItemDropdownDocumentation } from '../src/components/base/nav/nav_item_dropdown.documentation';
export { default as GlNavDocumentation } from '../src/components/base/nav/nav.documentation';
export { default as GlNavItemDocumentation } from '../src/components/base/nav/nav_item.documentation';
export { default as GlFormCheckboxTreeDocumentation } from '../src/components/base/form/form_checkbox_tree/form_checkbox_tree.documentation';
export { default as GlMarkdownDocumentation } from '../src/components/base/markdown/markdown.documentation';
export { default as GlNavbarDocumentation } from '../src/components/base/navbar/navbar.documentation';
export { default as GlIntersectionObserverDocumentation } from '../src/components/utilities/intersection_observer/intersection_observer.documentation';
export { default as GlChartDocumentation } from '../src/components/charts/chart/chart.documentation';
export { default as GlAreaChartDocumentation } from '../src/components/charts/area/area.documentation';
export { default as GlChartLegendDocumentation } from '../src/components/charts/legend/legend.documentation';
export { default as GlLineChartDocumentation } from '../src/components/charts/line/line.documentation';
export { default as GlSparklineChartDocumentation } from '../src/components/charts/sparkline/sparkline.documentation';
export { default as GlChartSeriesLabelDocumentation } from '../src/components/charts/series_label/series_label.documentation';
export { default as GlStackedColumnChartDocumentation } from '../src/components/charts/stacked_column/stacked_column.documentation';
export { default as GlBarChartDocumentation } from '../src/components/charts/bar/bar.documentation';
export { default as GlSingleStatDocumentation } from '../src/components/charts/single_stat/single_stat.documentation';
export { default as GlChartTooltipDocumentation } from '../src/components/charts/tooltip/tooltip.documentation';
export { default as GlToastDocumentation } from '../src/components/base/toast/toast.documentation';
export { default as GlAvatarDocumentation } from '../src/components/base/avatar/avatar.documentation';
export { default as GlAvatarsInlineDocumentation } from '../src/components/base/avatars_inline/avatars_inline.documentation';
export { default as GlAvatarLinkDocumentation } from '../src/components/base/avatar_link/avatar_link.documentation';
export { default as GlAvatarLabeledDocumentation } from '../src/components/base/avatar_labeled/avatar_labeled.documentation';
export { default as GlColumnChartDocumentation } from '../src/components/charts/column/column.documentation';
export { default as GlDiscreteScatterChartDocumentation } from '../src/components/charts/discrete_scatter/discrete_scatter.documentation';
export { default as GlSkeletonLoadingDocumentation } from '../src/components/base/skeleton_loading/skeleton_loading.documentation';
export { default as GlBadgeDocumentation } from '../src/components/base/badge/badge.documentation';
export { default as GlButtonDocumentation } from '../src/components/base/button/button.documentation';
export { default as GlLinkDocumentation } from '../src/components/base/link/link.documentation';
export { default as GlLoadingIconDocumentation } from '../src/components/base/loading_icon/loading_icon.documentation';
export { default as GlIconDocumentation } from '../src/components/base/icon/icon.documentation';
export { default as GlModalDocumentation } from '../src/components/base/modal/modal.documentation';
export { default as GlPaginationDocumentation } from '../src/components/base/pagination/pagination.documentation';
export { default as GlPaginatedListDocumentation } from '../src/components/base/paginated_list/paginated_list.documentation';
export { default as GlPathDocumentation } from '../src/components/base/path/path.documentation';
export { default as GlPopoverDocumentation } from '../src/components/base/popover/popover.documentation';
export { default as GlProgressBarDocumentation } from '../src/components/base/progress_bar/progress_bar.documentation';
export { default as GlTooltipDocumentation } from '../src/components/base/tooltip/tooltip.documentation';
export { default as GlDashboardSkeletonDocumentation } from '../src/components/regions/dashboard_skeleton/dashboard_skeleton.documentation';
export { default as GlEmptyStateDocumentation } from '../src/components/regions/empty_state/empty_state.documentation';
export { default as GlFormDocumentation } from '../src/components/base/form/form.documentation';
export { default as GlFormInputDocumentation } from '../src/components/base/form/form_input/form_input.documentation';
export { default as GlFormInputGroupDocumentation } from '../src/components/base/form/form_input_group/form_input_group.documentation';
export { default as GlFormTextareaDocumentation } from '../src/components/base/form/form_textarea/form_textarea.documentation';
export { default as GlFormGroupDocumentation } from '../src/components/base/form/form_group/form_group.documentation';
export { default as GlFormRadioDocumentation } from '../src/components/base/form/form_radio/form_radio.documentation';
export { default as GlFormRadioGroupDocumentation } from '../src/components/base/form/form_radio_group/form_radio_group.documentation';
export { default as GlFormSelectDocumentation } from '../src/components/base/form/form_select/form_select.documentation';
export { default as GlSearchBoxByTypeDocumentation } from '../src/components/base/search_box_by_type/search_box_by_type.documentation';
export { default as GlSearchBoxByClickDocumentation } from '../src/components/base/search_box_by_click/search_box_by_click.documentation';
export { default as GlDeprecatedDropdownItemDocumentation } from '../src/components/base/deprecated_dropdown/deprecated_dropdown_item.documentation';
export { default as GlDeprecatedDropdownHeaderDocumentation } from '../src/components/base/deprecated_dropdown/deprecated_dropdown_header.documentation';
export { default as GlDeprecatedDropdownDividerDocumentation } from '../src/components/base/deprecated_dropdown/deprecated_dropdown_divider.documentation';
export { default as GlDeprecatedDropdownDocumentation } from '../src/components/base/deprecated_dropdown/deprecated_dropdown.documentation';
export { default as GlDropdownDocumentation } from '../src/components/base/dropdown/dropdown.documentation';
export { default as GlDropdownItemDocumentation } from '../src/components/base/dropdown/dropdown_item.documentation';
export { default as GlDropdownDividerDocumentation } from '../src/components/base/dropdown/dropdown_divider.documentation';
export { default as GlDropdownSectionHeaderDocumentation } from '../src/components/base/dropdown/dropdown_section_header.documentation';
export { default as GlDropdownTextDocumentation } from '../src/components/base/dropdown/dropdown_text.documentation';
export { default as GlTableDocumentation } from '../src/components/base/table/table.documentation';
export { default as GlBreadcrumbDocumentation } from '../src/components/base/breadcrumb/breadcrumb.documentation';
export { default as GlHeatmapDocumentation } from '../src/components/charts/heatmap/heatmap.documentation';
export { default as GlTabsDocumentation } from '../src/components/base/tabs/tabs/tabs.documentation';
export { default as GlTabDocumentation } from '../src/components/base/tabs/tab/tab.documentation';
export { default as GlButtonGroupDocumentation } from '../src/components/base/button_group/button_group.documentation';
export { default as GlFormCheckboxDocumentation } from '../src/components/base/form/form_checkbox/form_checkbox.documentation';
export { default as GlLabelDocumentation } from '../src/components/base/label/label.documentation';
export { default as GlDatepickerDocumentation } from '../src/components/base/datepicker/datepicker.documentation';
export { default as GlTokenDocumentation } from '../src/components/base/token/token.documentation';
export { default as GlToggleDocumentation } from '../src/components/base/toggle/toggle.documentation';
export { default as GlDaterangePickerDocumentation } from '../src/components/base/daterange_picker/daterange_picker.documentation';
export { default as GlSortingDocumentation } from '../src/components/base/sorting/sorting.documentation';
export { default as GlSortingItemDocumentation } from '../src/components/base/sorting/sorting_item.documentation';
export { default as GlInfiniteScrollDocumentation } from '../src/components/base/infinite_scroll/infinite_scroll.documentation';
export { default as GlAlertDocumentation } from '../src/components/base/alert/alert.documentation';
export { default as GlSegmentedControlDocumentation } from '../src/components/base/segmented_control/segmented_control.documentation';
export { default as GlSkeletonLoaderDocumentation } from '../src/components/base/skeleton_loader/skeleton_loader.documentation';
export { default as GlDrawerDocumentation } from '../src/components/base/drawer/drawer.documentation';
export { default as GlCardDocumentation } from '../src/components/base/card/card.documentation';
export { default as GlOutsideDirectiveDocumentation } from '../src/directives/outside/outside.documentation';
export { default as GlResizeObserverDirectiveDocumentation } from '../src/directives/resize_observer/resize_observer.documentation';
export { default as GlBannerDocumentation } from '../src/components/base/banner/banner.documentation';
export { default as GlFilteredSearchSuggestionDocumentation } from '../src/components/base/filtered_search/filtered_search_suggestion.documentation';
export { default as GlFilteredSearchSuggestionListDocumentation } from '../src/components/base/filtered_search/filtered_search_suggestion_list.documentation';
export { default as GlFilteredSearchTermDocumentation } from '../src/components/base/filtered_search/filtered_search_term.documentation';
export { default as GlFilteredSearchTokenDocumentation } from '../src/components/base/filtered_search/filtered_search_token.documentation';
export { default as GlFilteredSearchTokenSegmentDocumentation } from '../src/components/base/filtered_search/filtered_search_token_segment.documentation';
export { default as GlFilteredSearchDocumentation } from '../src/components/base/filtered_search/filtered_search.documentation';
export { default as GlBroadcastMessageDocumentation } from '../src/components/base/broadcast_message/broadcast_message.documentation';
export { default as GlCollapseDocumentation } from '../src/components/base/collapse/collapse.documentation';
export { default as GlAccordionDocumentation } from '../src/components/base/accordion/accordion.documentation';
export { default as GlAccordionItemDocumentation } from '../src/components/base/accordion/accordion_item.documentation';
export { default as GlCarouselDocumentation } from '../src/components/base/carousel/carousel.documentation';
export { default as GlSafeLinkDirectiveDocumentation } from '../src/directives/safe_link/safe_link.documentation';
export { default as GlSafeHtmlDirectiveDocumentation } from '../src/directives/safe_html/safe_html.documentation';
export { default as GlAnimatedNumberDocumentation } from '../src/components/utilities/animated_number/animated_number.documentation';
export { default as GlFriendlyWrapDocumentation } from '../src/components/utilities/friendly_wrap/friendly_wrap.documentation';
export { default as GlIntersperseDocumentation } from '../src/components/utilities/intersperse/intersperse.documentation';
export { default as GlSprintfDocumentation } from '../src/components/utilities/sprintf/sprintf.documentation';
export { default as GlTruncateDocumentation } from '../src/components/utilities/truncate/truncate.documentation';
export { default as GlHoverLoadDirectiveDocumentation } from '../src/directives/hover_load/hover_load.documentation';

const componentList = Object.getPrototypeOf(module).exports;

export const getDocumentationFor = (componentName) => {
  const documentationKey = `${componentName}Documentation`;
  const documentationObject = componentList[documentationKey];
  if (!documentationObject) {
    throw new Error(
      `Could not find ${documentationKey} in documentation/components_documentation.js!`
    );
  }
  return documentationObject;
};
